/**
 * AUTO-GENERATED by scripts/generate-landing-snapshot.mjs — do not edit by hand.
 * Real Strategy Lab backtest results, snapshotted for the marketing landing page.
 * Regenerate:  npm run snapshot:landing
 */
export interface BacktestSnapshot {
  key: string;
  strategyTitle: string;
  strategyId: string;
  symbol: string;
  startDate: string;
  endDate: string;
  periodLabel: string;
  /** Fraction, e.g. 1.654 = +165.4% (engine field data.total_return_pct). */
  totalReturnPct: number;
  /** Fraction, e.g. 0.478 = 48% (engine field data.win_rate). */
  winRate: number;
  totalTrades: number;
}

/** Date this snapshot was last regenerated (YYYY-MM-DD). */
export const SNAPSHOT_AS_OF = "2026-06-28";

/** Featured result for the pinned "Test your idea" story card. */
export const LANDING_BACKTEST: BacktestSnapshot = {
  "key": "featured",
  "strategyTitle": "Fast EMA Cross (8 / 13)",
  "strategyId": "ema_8_13_cross",
  "symbol": "NVDA",
  "startDate": "2021-01-01",
  "endDate": "2024-12-31",
  "periodLabel": "2021–2024",
  "totalReturnPct": 1.6543,
  "winRate": 0.478,
  "totalTrades": 23
};

/** Strategy preview cards (TradlyteSelect), keyed by its card id. */
export const FEATURED_STRATEGIES: BacktestSnapshot[] = [
  {
    "key": "momentum",
    "strategyTitle": "Momentum Rider",
    "strategyId": "ema_8_13_cross",
    "symbol": "AMD",
    "startDate": "2021-01-01",
    "endDate": "2024-12-31",
    "periodLabel": "2021–2024",
    "totalReturnPct": 1.1184,
    "winRate": 0.385,
    "totalTrades": 26
  },
  {
    "key": "golden",
    "strategyTitle": "Golden Cross",
    "strategyId": "golden_cross_20_50",
    "symbol": "GOOG",
    "startDate": "2021-01-01",
    "endDate": "2024-12-31",
    "periodLabel": "2021–2024",
    "totalReturnPct": 0.3557,
    "winRate": 0.167,
    "totalTrades": 6
  },
  {
    "key": "mean",
    "strategyTitle": "Mean Reversion",
    "strategyId": "rsi_oversold_bounce",
    "symbol": "NVDA",
    "startDate": "2021-01-01",
    "endDate": "2024-12-31",
    "periodLabel": "2021–2024",
    "totalReturnPct": 1.6869,
    "winRate": 0.25,
    "totalTrades": 4
  }
];
